# Generated migration for documents app - initial schema

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Case', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('review', 'Ready for Review'), ('complete', 'Complete')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('plaintiff_info', 'Plaintiff Information'), ('incident_overview', 'Incident Overview'), ('defendants', 'Government Defendants'), ('incident_narrative', 'Incident Narrative'), ('rights_violated', 'Rights Violated'), ('witnesses', 'Witnesses'), ('evidence', 'Evidence'), ('damages', 'Damages'), ('prior_complaints', 'Prior Complaints'), ('relief_sought', 'Relief Sought')], max_length=30)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about what needs work')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='documents.document')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('document', 'section_type')},
            },
        ),
        migrations.CreateModel(
            name='PlaintiffInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_pro_se', models.BooleanField(default=True, help_text='Representing yourself without an attorney')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plaintiff_info', to='documents.documentsection')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('location_type', models.CharField(blank=True, help_text='e.g., Public sidewalk, Government building, etc.', max_length=100)),
                ('was_recording', models.BooleanField(default=False)),
                ('recording_device', models.CharField(blank=True, max_length=100)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incident_overview', to='documents.documentsection')),
            ],
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defendant_type', models.CharField(choices=[('agency', 'Government Agency'), ('individual', 'Individual Officer')], max_length=20)),
                ('name', models.CharField(help_text='Agency name or officer name', max_length=255)),
                ('badge_number', models.CharField(blank=True, max_length=50)),
                ('title_rank', models.CharField(blank=True, help_text='e.g., Sergeant, Detective, etc.', max_length=100)),
                ('agency_name', models.CharField(blank=True, help_text='For individual officers, their employing agency', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Official address for service')),
                ('description', models.TextField(blank=True, help_text='Physical description or identifying information')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defendants', to='documents.documentsection')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, help_text='Brief summary of the incident (2-3 sentences)')),
                ('detailed_narrative', models.TextField(blank=True, help_text='Full detailed account of what happened')),
                ('what_were_you_doing', models.TextField(blank=True, help_text='What were you doing before/during the incident?')),
                ('initial_contact', models.TextField(blank=True, help_text='How did the encounter begin?')),
                ('what_was_said', models.TextField(blank=True, help_text='What was said by officers and by you?')),
                ('physical_actions', models.TextField(blank=True, help_text='Describe any physical actions taken')),
                ('how_it_ended', models.TextField(blank=True, help_text='How did the encounter end?')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incident_narrative', to='documents.documentsection')),
            ],
        ),
        migrations.CreateModel(
            name='RightsViolated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_amendment', models.BooleanField(default=False, verbose_name='First Amendment')),
                ('first_amendment_speech', models.BooleanField(default=False, verbose_name='Freedom of Speech')),
                ('first_amendment_press', models.BooleanField(default=False, verbose_name='Freedom of Press')),
                ('first_amendment_assembly', models.BooleanField(default=False, verbose_name='Freedom of Assembly')),
                ('first_amendment_petition', models.BooleanField(default=False, verbose_name='Right to Petition')),
                ('first_amendment_details', models.TextField(blank=True, help_text='Explain how First Amendment rights were violated')),
                ('fourth_amendment', models.BooleanField(default=False, verbose_name='Fourth Amendment')),
                ('fourth_amendment_search', models.BooleanField(default=False, verbose_name='Unreasonable Search')),
                ('fourth_amendment_seizure', models.BooleanField(default=False, verbose_name='Unreasonable Seizure')),
                ('fourth_amendment_arrest', models.BooleanField(default=False, verbose_name='False Arrest')),
                ('fourth_amendment_force', models.BooleanField(default=False, verbose_name='Excessive Force')),
                ('fourth_amendment_details', models.TextField(blank=True, help_text='Explain how Fourth Amendment rights were violated')),
                ('fifth_amendment', models.BooleanField(default=False, verbose_name='Fifth Amendment')),
                ('fifth_amendment_self_incrimination', models.BooleanField(default=False, verbose_name='Self-Incrimination')),
                ('fifth_amendment_due_process', models.BooleanField(default=False, verbose_name='Due Process')),
                ('fifth_amendment_details', models.TextField(blank=True, help_text='Explain how Fifth Amendment rights were violated')),
                ('fourteenth_amendment', models.BooleanField(default=False, verbose_name='Fourteenth Amendment')),
                ('fourteenth_amendment_due_process', models.BooleanField(default=False, verbose_name='Due Process')),
                ('fourteenth_amendment_equal_protection', models.BooleanField(default=False, verbose_name='Equal Protection')),
                ('fourteenth_amendment_details', models.TextField(blank=True, help_text='Explain how Fourteenth Amendment rights were violated')),
                ('other_rights', models.TextField(blank=True, help_text='Any other rights or laws violated')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rights_violated', to='documents.documentsection')),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField(blank=True, help_text='Phone, email, or address')),
                ('relationship', models.CharField(blank=True, help_text='How do you know this person?', max_length=100)),
                ('what_they_witnessed', models.TextField(blank=True)),
                ('willing_to_testify', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='documents.documentsection')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('video', 'Video Recording'), ('audio', 'Audio Recording'), ('photo', 'Photograph'), ('document', 'Document'), ('social_media', 'Social Media Post'), ('body_cam', 'Body Camera Footage'), ('dash_cam', 'Dash Camera Footage'), ('surveillance', 'Surveillance Footage'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('location_obtained', models.CharField(blank=True, max_length=255)),
                ('is_in_possession', models.BooleanField(default=True)),
                ('needs_subpoena', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='documents.documentsection')),
            ],
        ),
        migrations.CreateModel(
            name='Damages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_injury', models.BooleanField(default=False)),
                ('physical_injury_description', models.TextField(blank=True)),
                ('medical_treatment', models.BooleanField(default=False)),
                ('medical_treatment_description', models.TextField(blank=True)),
                ('ongoing_medical_issues', models.BooleanField(default=False)),
                ('ongoing_medical_description', models.TextField(blank=True)),
                ('emotional_distress', models.BooleanField(default=False)),
                ('emotional_distress_description', models.TextField(blank=True)),
                ('property_damage', models.BooleanField(default=False)),
                ('property_damage_description', models.TextField(blank=True)),
                ('lost_wages', models.BooleanField(default=False)),
                ('lost_wages_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('legal_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medical_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_expenses_description', models.TextField(blank=True)),
                ('reputation_harm', models.BooleanField(default=False)),
                ('reputation_harm_description', models.TextField(blank=True)),
                ('other_damages', models.TextField(blank=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='documents.documentsection')),
            ],
        ),
        migrations.CreateModel(
            name='PriorComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_internal_complaint', models.BooleanField(default=False)),
                ('internal_complaint_date', models.DateField(blank=True, null=True)),
                ('internal_complaint_description', models.TextField(blank=True)),
                ('internal_complaint_outcome', models.TextField(blank=True)),
                ('filed_civilian_complaint', models.BooleanField(default=False)),
                ('civilian_complaint_date', models.DateField(blank=True, null=True)),
                ('civilian_complaint_description', models.TextField(blank=True)),
                ('civilian_complaint_outcome', models.TextField(blank=True)),
                ('contacted_media', models.BooleanField(default=False)),
                ('media_contact_description', models.TextField(blank=True)),
                ('other_actions', models.TextField(blank=True, help_text='Any other actions taken to address the incident')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prior_complaints', to='documents.documentsection')),
            ],
        ),
        migrations.CreateModel(
            name='ReliefSought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensatory_damages', models.BooleanField(default=True)),
                ('compensatory_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('punitive_damages', models.BooleanField(default=False)),
                ('punitive_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('attorney_fees', models.BooleanField(default=True)),
                ('injunctive_relief', models.BooleanField(default=False)),
                ('injunctive_description', models.TextField(blank=True, help_text='What specific actions do you want the court to order?')),
                ('declaratory_relief', models.BooleanField(default=False)),
                ('declaratory_description', models.TextField(blank=True, help_text='What do you want the court to declare?')),
                ('other_relief', models.TextField(blank=True)),
                ('jury_trial_demanded', models.BooleanField(default=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relief_sought', to='documents.documentsection')),
            ],
        ),
    ]
