# Generated by Django 4.2.27 on 2026-01-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompt',
            name='prompt_type',
            field=models.CharField(choices=[('parse_story', 'Parse Story - Analyzes user story and extracts structured data'), ('analyze_rights', 'Analyze Rights - Identifies constitutional violations'), ('suggest_agency', 'Suggest Agency - Finds defendants based on story'), ('suggest_relief', 'Suggest Relief - Recommends legal relief options'), ('find_law_enforcement', 'Find Law Enforcement - Identifies correct police/sheriff'), ('lookup_address', 'Lookup Address - Finds agency addresses'), ('lookup_federal_court', 'Lookup Federal Court - Finds federal district court for location')], help_text='Which AI function this prompt is used for', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='promocodeusage',
            name='referral_amount',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
        ),
    ]
