# Generated by Django 4.2.27 on 2026-01-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_aiprompt_prompt_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodeusage',
            name='referral_amount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
