# Generated by Django 4.2.27 on 2026-01-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_video_evidence'),
        ('documents', '0003_alter_promocodeusage_referral_amount'),
    ]

    operations = [
    ]
