# Generated by Django 4.2.27 on 2026-01-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_evidence_time_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="final_causes_of_action",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of causes of action (each with title and text)",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="final_edited_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When final document text was last edited by user",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="final_facts",
            field=models.TextField(blank=True, help_text="Statement of Facts section"),
        ),
        migrations.AddField(
            model_name="document",
            name="final_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When final document text was generated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="final_introduction",
            field=models.TextField(
                blank=True, help_text="Introduction paragraph for the complaint"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="final_jurisdiction",
            field=models.TextField(
                blank=True, help_text="Jurisdiction and Venue section text"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="final_jury_demand",
            field=models.TextField(
                blank=True, help_text="Jury Demand section (if applicable)"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="final_parties",
            field=models.TextField(
                blank=True,
                help_text="Parties section describing plaintiff and defendants",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="final_prayer",
            field=models.TextField(blank=True, help_text="Prayer for Relief section"),
        ),
        migrations.AddField(
            model_name="document",
            name="final_signature",
            field=models.TextField(blank=True, help_text="Signature block text"),
        ),
        migrations.AlterField(
            model_name="documentsection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("plaintiff_info", "Plaintiff Information"),
                    ("incident_overview", "Incident Overview"),
                    ("defendants", "Government Defendants"),
                    ("incident_narrative", "Incident Narrative"),
                    ("evidence", "Evidence"),
                    ("rights_violated", "Rights Violated"),
                    ("witnesses", "Witnesses"),
                    ("damages", "Damages"),
                    ("prior_complaints", "Prior Complaints"),
                    ("relief_sought", "Relief Sought"),
                ],
                max_length=30,
            ),
        ),
    ]
