# Generated by Django 4.2.27 on 2026-01-12 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_story_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(help_text='e.g., Graham v. Connor', max_length=255)),
                ('citation', models.CharField(help_text='e.g., 490 U.S. 386 (1989)', max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('court_level', models.CharField(choices=[('supreme', 'U.S. Supreme Court'), ('circuit', 'Circuit Court of Appeals'), ('district', 'District Court')], max_length=20)),
                ('circuit', models.CharField(blank=True, help_text='e.g., 9th Circuit, if applicable', max_length=50)),
                ('amendment', models.CharField(choices=[('first', 'First Amendment'), ('fourth', 'Fourth Amendment'), ('fifth', 'Fifth Amendment'), ('fourteenth', 'Fourteenth Amendment')], max_length=20)),
                ('right_category', models.CharField(choices=[('speech', 'Freedom of Speech'), ('press', 'Freedom of Press'), ('assembly', 'Freedom of Assembly'), ('petition', 'Right to Petition'), ('recording', 'Right to Record Police'), ('excessive_force', 'Excessive Force'), ('false_arrest', 'False Arrest'), ('unlawful_detention', 'Unlawful Detention'), ('unreasonable_search', 'Unreasonable Search'), ('unreasonable_seizure', 'Unreasonable Seizure'), ('self_incrimination', 'Self-Incrimination'), ('due_process_fifth', 'Due Process (Fifth)'), ('due_process', 'Due Process'), ('equal_protection', 'Equal Protection'), ('qualified_immunity', 'Qualified Immunity'), ('municipal_liability', 'Municipal Liability'), ('section_1983_general', 'Section 1983 General')], max_length=50)),
                ('key_holding', models.TextField(help_text='The main legal principle established')),
                ('facts_summary', models.TextField(help_text='Brief summary of the case facts')),
                ('relevance_keywords', models.TextField(help_text='Comma-separated keywords for AI matching')),
                ('citation_text', models.TextField(help_text='Ready-to-use citation paragraph for complaints')),
                ('is_landmark', models.BooleanField(default=False, help_text='Is this a foundational/frequently cited case?')),
                ('is_active', models.BooleanField(default=True, help_text='Include in AI suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case Law',
                'verbose_name_plural': 'Case Law',
                'ordering': ['-is_landmark', '-year'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCaseLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment', models.CharField(choices=[('first', 'First Amendment'), ('fourth', 'Fourth Amendment'), ('fifth', 'Fifth Amendment'), ('fourteenth', 'Fourteenth Amendment')], max_length=20)),
                ('right_category', models.CharField(choices=[('speech', 'Freedom of Speech'), ('press', 'Freedom of Press'), ('assembly', 'Freedom of Assembly'), ('petition', 'Right to Petition'), ('recording', 'Right to Record Police'), ('excessive_force', 'Excessive Force'), ('false_arrest', 'False Arrest'), ('unlawful_detention', 'Unlawful Detention'), ('unreasonable_search', 'Unreasonable Search'), ('unreasonable_seizure', 'Unreasonable Seizure'), ('self_incrimination', 'Self-Incrimination'), ('due_process_fifth', 'Due Process (Fifth)'), ('due_process', 'Due Process'), ('equal_protection', 'Equal Protection'), ('qualified_immunity', 'Qualified Immunity'), ('municipal_liability', 'Municipal Liability'), ('section_1983_general', 'Section 1983 General')], max_length=50)),
                ('relevance_explanation', models.TextField(help_text='AI-generated explanation of how this case applies to the facts')),
                ('user_explanation', models.TextField(blank=True, help_text='User-edited explanation (overrides AI)')),
                ('status', models.CharField(choices=[('suggested', 'AI Suggested'), ('accepted', 'Accepted'), ('edited', 'Edited by User'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_uses', to='documents.caselaw')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_law_citations', to='documents.document')),
            ],
            options={
                'ordering': ['amendment', 'order'],
                'unique_together': {('document', 'case_law')},
            },
        ),
    ]
