# Generated by Django 4.2.27 on 2026-01-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_add_final_document_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="applied_video_suggestions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Log of applied video evidence suggestions",
            ),
        ),
    ]
