# Generated by Django 4.2.27 on 2026-01-30

import secrets
import string

from django.db import migrations, models


def generate_slug(length=8):
    alphabet = string.ascii_letters + string.digits
    return ''.join(secrets.choice(alphabet) for _ in range(length))


def populate_slugs(apps, schema_editor):
    """Generate unique slugs for all existing records."""
    models_to_update = [
        ('Document', 'document'),
        ('Defendant', 'defendant'),
        ('Witness', 'witness'),
        ('Evidence', 'evidence'),
        ('VideoEvidence', 'videoevidence'),
        ('VideoCapture', 'videocapture'),
        ('VideoSpeaker', 'videospeaker'),
    ]

    for model_name, _ in models_to_update:
        Model = apps.get_model('documents', model_name)
        used_slugs = set()
        for obj in Model.objects.all():
            slug = generate_slug()
            while slug in used_slugs:
                slug = generate_slug()
            used_slugs.add(slug)
            obj.slug = slug
            obj.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_document_applied_video_suggestions"),
    ]

    operations = [
        # Step 1: Add slug fields as nullable
        migrations.AddField(
            model_name="document",
            name="slug",
            field=models.CharField(max_length=12, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="defendant",
            name="slug",
            field=models.CharField(max_length=12, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="witness",
            name="slug",
            field=models.CharField(max_length=12, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="evidence",
            name="slug",
            field=models.CharField(max_length=12, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="videoevidence",
            name="slug",
            field=models.CharField(max_length=12, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="videocapture",
            name="slug",
            field=models.CharField(max_length=12, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="videospeaker",
            name="slug",
            field=models.CharField(max_length=12, null=True, blank=True),
        ),

        # Step 2: Populate slugs for existing records
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),

        # Step 3: Make slug fields non-nullable, unique, and indexed
        migrations.AlterField(
            model_name="document",
            name="slug",
            field=models.CharField(max_length=12, unique=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="defendant",
            name="slug",
            field=models.CharField(max_length=12, unique=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="witness",
            name="slug",
            field=models.CharField(max_length=12, unique=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="slug",
            field=models.CharField(max_length=12, unique=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="videoevidence",
            name="slug",
            field=models.CharField(max_length=12, unique=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="videocapture",
            name="slug",
            field=models.CharField(max_length=12, unique=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="videospeaker",
            name="slug",
            field=models.CharField(max_length=12, unique=True, db_index=True),
        ),
    ]
