# Generated by Django 4.2.27 on 2026-01-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_caselaw_documentcaselaw'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsection',
            name='story_relevance',
            field=models.CharField(choices=[('unknown', 'Not Analyzed'), ('relevant', 'Relevant'), ('may_not_apply', 'May Not Apply')], default='unknown', help_text='Whether this section appears relevant based on story analysis', max_length=20),
        ),
    ]
