# Generated by Django 5.2.10 on 2026-02-02 16:31

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_add_slugs_to_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defendant",
            name="slug",
            field=models.CharField(
                db_index=True,
                default=documents.models.generate_slug,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="ai_generations_used",
            field=models.IntegerField(
                default=0,
                help_text="AI generations used (for free tier and paid documents)",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="slug",
            field=models.CharField(
                db_index=True,
                default=documents.models.generate_slug,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="slug",
            field=models.CharField(
                db_index=True,
                default=documents.models.generate_slug,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="videocapture",
            name="slug",
            field=models.CharField(
                db_index=True,
                default=documents.models.generate_slug,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="videoevidence",
            name="slug",
            field=models.CharField(
                db_index=True,
                default=documents.models.generate_slug,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="videospeaker",
            name="slug",
            field=models.CharField(
                db_index=True,
                default=documents.models.generate_slug,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="witness",
            name="slug",
            field=models.CharField(
                db_index=True,
                default=documents.models.generate_slug,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="WizardSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        db_index=True,
                        default=documents.models.generate_slug,
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("analyzing", "Analyzing"),
                            ("analyzed", "Analyzed"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("current_step", models.PositiveIntegerField(default=1)),
                ("raw_story", models.TextField(blank=True)),
                ("ai_extracted", models.JSONField(blank=True, default=dict)),
                ("interview_data", models.JSONField(blank=True, default=dict)),
                ("use_case_law", models.BooleanField(default=True)),
                ("ai_analysis", models.JSONField(blank=True, default=dict)),
                (
                    "analysis_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("analysis_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wizard_session",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wizard Session",
                "verbose_name_plural": "Wizard Sessions",
            },
        ),
    ]
