# Generated by Django 4.2.27 on 2026-01-13 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0008_documentsection_story_relevance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique promo code (e.g., SMITH25)', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('times_used', models.IntegerField(default=0)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.AddField(
            model_name='document',
            name='ai_cost_used',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Paid tier: actual API cost in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_generations_used',
            field=models.IntegerField(default=0, help_text='Free tier: count of generations used'),
        ),
        migrations.AddField(
            model_name='document',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='payment_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('expired', 'Expired'), ('paid', 'Paid'), ('finalized', 'Finalized')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='stripe_payment_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='reliefsought',
            name='attorney_fees',
            field=models.BooleanField(default=True, help_text='42 U.S.C. § 1988 allows recovery of legal fees in civil rights cases - ALWAYS include this', verbose_name="Attorney's Fees"),
        ),
        migrations.AlterField(
            model_name='reliefsought',
            name='compensatory_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to let the court/jury decide the amount', max_digits=12, null=True, verbose_name='Specific Amount (optional)'),
        ),
        migrations.AlterField(
            model_name='reliefsought',
            name='compensatory_damages',
            field=models.BooleanField(default=True, help_text='Money to cover actual losses - medical bills, lost wages, emotional distress, damaged equipment', verbose_name='Compensatory Damages'),
        ),
        migrations.AlterField(
            model_name='reliefsought',
            name='declaratory_description',
            field=models.TextField(blank=True, help_text='Customize what you want declared, or leave blank for standard language', verbose_name='Declaration Details (optional)'),
        ),
        migrations.AlterField(
            model_name='reliefsought',
            name='declaratory_relief',
            field=models.BooleanField(default=True, help_text='Official court declaration that your constitutional rights were violated', verbose_name='Declaratory Judgment'),
        ),
        migrations.AlterField(
            model_name='reliefsought',
            name='injunctive_description',
            field=models.TextField(blank=True, help_text='Example: Require training on First Amendment rights, revise filming policies', verbose_name='What changes do you want?'),
        ),
        migrations.AlterField(
            model_name='reliefsought',
            name='injunctive_relief',
            field=models.BooleanField(default=False, help_text='Court orders forcing the department to change policies or training - harder to get but creates lasting change', verbose_name='Injunctive Relief (Policy Changes)'),
        ),
        migrations.AlterField(
            model_name='reliefsought',
            name='jury_trial_demanded',
            field=models.BooleanField(default=True, help_text='Have regular citizens decide your case - juries are often sympathetic to civil rights plaintiffs', verbose_name='Jury Trial'),
        ),
        migrations.AlterField(
            model_name='reliefsought',
            name='other_relief',
            field=models.TextField(blank=True, help_text='Any other relief not covered above', verbose_name='Other Relief'),
        ),
        migrations.AlterField(
            model_name='reliefsought',
            name='punitive_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to let the court/jury decide the amount', max_digits=12, null=True, verbose_name='Specific Amount (optional)'),
        ),
        migrations.AlterField(
            model_name='reliefsought',
            name='punitive_damages',
            field=models.BooleanField(default=True, help_text='Extra money to punish officers who clearly violated your rights', verbose_name='Punitive Damages'),
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_id', models.CharField(max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referral_amount', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('payout_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('payout_reference', models.CharField(blank=True, help_text='Reference for payout (PayPal transaction ID, check number, etc.)', max_length=255)),
                ('payout_date', models.DateTimeField(blank=True, null=True)),
                ('payout_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usage', to='documents.document')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='documents.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code Usage',
                'verbose_name_plural': 'Promo Code Usages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='promo_code_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_used', to='documents.promocode'),
        ),
    ]
