# Generated by Django - migration stub for stale database record
# This migration was auto-generated in Docker but never committed

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_promocode_referral_amount'),
    ]

    operations = [
    ]
