# Generated by Django - merge migration stub
# This migration was recorded in the database but the file was missing

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_defendant_agency_inferred'),
    ]

    operations = [
    ]
